variable "keypair" {}
variable "name" {}
variable "subnet_id" {}
variable "vpc" {}
variable "bastion" {}
variable "private-key" {}
variable "deployment" {}
variable "prod-bashscript" {}
variable "stage-bashscript" {}
variable "nexus-ip" {}
variable "nr-key" {}
variable "nr-acc-id" {}